import "./globals.css";
import AuthGuard from "@/utils/authguard";
import SessionWrapper from "@/utils/sessionwrapper";
import { NavPathChecker } from "@/utils/sessionwrapper";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ['latin'] });
// import { Geist, Geist_Mono } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "MealMail",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      // className={`${inter.className}`}
      >
        <SessionWrapper>
          <NavPathChecker />
          <AuthGuard>{children}</AuthGuard>
        </SessionWrapper>
      </body>
    </html>
  );
}
